### ISSUE TITLE
PR's description should contain fixes tag.

### ISSUE THREAD

**Issue by Anshgrover23** [tscircuit/tscircuit.com#445]
#### Description

- All the PRs should include `Fixes #issueNumber`
- This thing is mandatory because some issues are solved but they are not closed yet.

**Comment by Anshgrover23** [comment]
CC: @seveibar yours take!

**Comment by seveibar** [comment]
yea prs should generally contain that tag 👍, but not sure how to enforce that. Also probably not mandatory because people fixing small things might not have an associated issue 🤔

**Comment by Anshgrover23** [comment]
@seveibar ok but we can like create  general pull request template that automatically pre-fills the PR description when someone creates a new pull request, example:
`## Description

Please provide a short summary of the changes in this pull request.

---

## Checklist

- [ ] My code follows the repository's style guidelines.
- [ ] I have performed a self-review of my code.
- [ ] I have added comments in my code where necessary.
- [ ] I have updated the documentation, if needed.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

---

## Linked Issues

Resolves # (issue number)

---

## Screenshots (if applicable)

Add screenshots to showcase the feature or bug fix.
`
